version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fuelphp-app
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html/my_fuel_project
    networks:
      - fuelphp-network

  db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: equipment_db
    ports:
      - "3306:3306"
    networks:
      - fuelphp-network

#↓  6/22 db管理のため追加
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fuelphp-phpmyadmin
    links:
      - db:db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - fuelphp-network

networks:
  fuelphp-network:
    driver: bridge
